### ISSUE TITLE
TerminalApplicationDelegate

### ISSUE THREAD

**Issue by christhwaites** [Square-Six/Xamarin.Stripe.Terminal.Android#4]
Hi There,

I'm not sure if I'm missing something, but when I open the Sample app (which has a nuget reference to the built stripe bindings projectXamarin.Stripe.Terminal.Android) I can't find the TerminalApplicationDelegate, which I think I need to call in my Application file to notify the SDK about lifecycle events.

For example, I'm expecting to put something like this in my code:

```
namespace Xamarin.Stripe.Terminal.Android.Demo
{
    public class StripeTerminalApplication : Application
    {
        public override void OnCreate()
        {
            base.OnCreate();
            TerminalApplicationDelegate.OnCreate(this);
        }
    }
}
```

But I can't see where this is defined in the Xamarin.Stripe.Terminal.Android nuget package I've referenced.

I'm sure I'm missing something blindingly obvious... but I can't see what it is!

Any help would be very gratefully received!

Cheers,
    Chris

**Comment by chris-oswald** [comment]
The sample app hasn't been updated. I only updated the bindings. @davidsonblake might be able to tell you if he plans to maintain the sample app.

**Comment by christhwaites** [comment]
Oh, OK. Thanks for getting back!

**Comment by chris-oswald** [comment]
I'm working on the 2.9 bindings right now. I should have those done in about 2 weeks.
